[핸드폰 번호 인증] 핸드폰 번호 인증 비즈니스 로직 및 API 구성(#44)
Yeonba/yeonba-api-server pull request #49
Opened 2024-03-27 11:35 UTC by Minjae-An

## 작업 대상

- 인증 코드 sms 전송 비즈니스 로직
- 인증 코드 sms 전송 API
- 핸드폰 번호 인증 비즈니스 로직
- 핸드폰 번호 인증 API

## 📄 작업 내용

회원가입 과정서 사용하는 인증 코드 sms 전송, 핸드폰 번호 인증 비즈니스 로직, API 구성

## 🙋🏻 주의 사항

- 이메일 찾기를 위한 인증 코드 sms 전송 API와 같은 `UserVerificationCodeRequest`, 인증 코드 sms 전송 API에서 사용

## 📎 관련 이슈

## 레퍼런스

2024-03-29 12:05 UTC, acceptor-gyu commented
중복되는 내용이 너무 많아서 리뷰 하기가 힘듭니다. 이전 PR 해결 후 다시 올려주시기 바랍니다. 해당 PR은 close 하겠습니다.

2024-03-31 07:21 UTC, acceptor-gyu reviewed
controller 부분 depth가 8입니다. 수정부탁드립니다.

2024-03-31 16:02 UTC, acceptor-gyu approved these changes

2024-03-31 16:02 UTC, acceptor-gyu commented on be/src/main/java/yeonba/be/login/service/LoginService.java
> +        }
`만료된 코드입니다.`라는 메시지를 명시해줘야 하는 이유가 없다면 위 로직을 한 번에 처리하는 것은 어떨까요?

`verificationCodeQuery.findByPhoneNumberAndVerificationCodeAndBeforeIsExpired(...)`

2024-03-31 16:02 UTC, acceptor-gyu commented on be/src/main/java/yeonba/be/login/controller/LoginController.java
> +    @PostMapping("/users/help/pw-inquiry")
path에 `help` 를 추가하신 이유가 무엇인가요?

2024-04-01 05:19 UTC, Minjae-An commented on be/src/main/java/yeonba/be/login/controller/LoginController.java
> +    @PostMapping("/users/help/pw-inquiry")
실수입니다. 수정하겠습니다!

2024-04-01 05:20 UTC, Minjae-An commented on be/src/main/java/yeonba/be/login/service/LoginService.java
> +        }
`만료된 코드 = 존재하지 않는 코드`로 취급할 수 있어 일리 있는 의견이라고 생각합니다. 반영하겠습니다.

2024-04-01 08:08 UTC, acceptor-gyu reviewed
깐깐한 리뷰어 만나서 고생하십니다. 해당 PR에 대해 마지막 comment이길 바라며...

2024-04-01 08:08 UTC, acceptor-gyu commented on be/src/main/java/yeonba/be/login/repository/VerificationCodeRepository.java
> +        String phoneNumber,
이렇게 쿼리 메서드를 작성하면 만료되지 않은 code 중 가장 처음 사용자에게 응답된 코드가 응답될 것같습니다.
제 생각에는 사용자 입장에서 여러 번 코드 요청을 한 상황이라면 가장 최근에 메시지를 통해 응답받은 code로 인증 요청을 하는 것이 일반적인 상황일 것같고, 그렇다면 사용자는 정상적인 code로 인증 시도를 하더라도 인증이 되지 않는 경험을 하게될 것같습니다.
서비스에 치명적인 문제는 없지만, 이 부분에 대해서 어떻게 생각하시나요?

2024-04-01 08:08 UTC, acceptor-gyu commented on be/src/main/java/yeonba/be/login/service/LoginService.java
> +    }
주기적으로 verification code를 삭제해야 하는 이유는 무엇인가요?
제 생각에는 verifcation code 데이터가 생기는 경우가 잦지 않을 것으로 예상되는 점, 데이터의 크기가 크거나 속도가 중요한 부분이 아니라서 계속 남아있거나 삭제 주기를 더 길게 가져가는 것이 더 낫다고 생각하는데 어떻게 생각하시나요?

2024-04-01 08:08 UTC, acceptor-gyu commented on be/src/main/java/yeonba/be/login/repository/VerificationCodeQuery.java
> +        String phoneNumber,
soft delete와는 성격이 다르긴 하지만, expired된 code가 의미없는, 서비스에서 사용되지 않을 데이터라면 메서드 명에서 soft delte를 하는 데이터가 있다면 `findByIdAndDeletedAtIsNull`을 메서드 명으로 하지 않는 것처럼 `NotExpired`라는 단어를 쓰지 않는 것이 더 일관성 있는 것같은데 어떻게 생각하시나요?

지극히 주관적인 생각이고, 현재 메서드 명이 더 명시적으로 표현하고 있다는 것도 맞는 말이라서 생각해보시고 현재 메서드명이 적합하다고 생각이 드시면 수정하지 않으셔도 됩니다. (쓸까 말까 고민하다가 comment 남깁니다.)

2024-04-01 08:12 UTC, Minjae-An commented on be/src/main/java/yeonba/be/login/service/LoginService.java
> +    }
- DB에 서비스에서 전혀 활용하지 되지 않는 데이터가 누적되며 리소스를 낭비하는 상황은 적절치 않다고 봅니다.
- 이에 따라 verification code를 주기적으로 삭제하는 작업은 필요하다고 생각합니다.
- 의견 주신 대로 주기를 더 길게 가져가는 것은 적절하다고 봅니다. 한 달로 주기를 재설정하겠습니다.

2024-04-01 08:13 UTC, acceptor-gyu requested changes
추가된 로직에 대해서 문제가 있어보여 request changes 하겠습니다. GitHub 기능을 잘못 사용해서 comment만 남긴 제 불찰입니다.

2024-04-01 08:13 UTC, Minjae-An commented on be/src/main/java/yeonba/be/login/repository/VerificationCodeRepository.java
> +        String phoneNumber,
동의합니다. 수정하겠습니다.

2024-04-01 08:15 UTC, Minjae-An commented on be/src/main/java/yeonba/be/login/repository/VerificationCodeQuery.java
> +        String phoneNumber,
일관성 있게 맞추는 것이 적절하다고 봅니다. 수정하겠습니다.

2024-04-01 08:34 UTC, Minjae-An commented on be/src/main/java/yeonba/be/login/repository/VerificationCodeRepository.java
> +        String phoneNumber,
생각해보니 `verificationCode`를 고유하게 식별할 수 있는 `code`가 파라미터에 포함되어 있어 굳이 정렬 처리를 하지 않아도 됩니다. 보완할 부분이 있으면 그 부분만 시정하여 올리겠습니다!

2024-04-01 08:45 UTC, acceptor-gyu approved these changes
고생하셨습니다.~!

2024-04-01 10:53 UTC, acceptor-gyu approved these changes
고생하셨습니다 ^^

2024-04-03 04:18 UTC, merged