[로그인 및 access token refresh] 로그인 및 access token refresh 비즈니스 로직/API 구성
Yeonba/yeonba-api-server pull request #56
Opened 2024-04-05 08:33 UTC by Minjae-An

## 작업 대상

- 로그인 비즈니스 로직 및 API
- access token refresh 비즈니스 로직 및 API
- 인가 로직

## 📄 작업 내용

- 로그인 비즈니스 로직 및 API 구현
- refresh token 바탕 access token을 재발급 받는 비즈니스 로직 및 API 구현
- access token으로 사용자에게 인가 과정을 수행하는 `BearerTokenAuthInterceptor` 구현

## 🙋🏻 주의 사항

## 📎 관련 이슈

## 레퍼런스

2024-04-05 08:34 UTC, Minjae-An commented
수정 사항 반영 후 reopen

2024-04-05 10:18 UTC, Minjae-An commented
출석 체크 비즈니스 로직 수정사항으로 인해 close

2024-04-06 15:20 UTC, acceptor-gyu requested changes
형식 및 사소한 실수나 이전에 얘기됐지만 수정되지 않은 부분들 수정하시면 다시 확인하겠습니다.

2024-04-06 15:20 UTC, acceptor-gyu commented on be/src/main/java/yeonba/be/login/dto/request/UserLoginRequest.java
> +	@NotBlank(message = "이메일은 반드시 입력되어야 합니다.")
tap 사용하지 않기로 했는데 사용된 것같습니다. 확인부탁드립니다.

2024-04-06 15:20 UTC, acceptor-gyu commented on be/src/main/java/yeonba/be/login/service/LoginService.java
> +        String refreshToken = jwtUtil.generateRefreshToken(user, issuedAt);
issuedAt이라는 변수명은 수정하기로 얘기된 거 아니었나요?

2024-04-06 15:26 UTC, acceptor-gyu commented
단순히 기능 구현만 생각을 하지 마시고 리뷰하는 사람을 생각해서 본인의 PR을 다시 한 번 검토하는 시간을 가져보는 것도 좋을 것같습니다.

2024-04-07 05:54 UTC, Minjae-An commented
말씀하신 대로 너무 기능 구현에 급급하였던 것 같습니다. PR을 올릴 때 더 세심히 검토하겠습니다. 죄송합니다.

2024-04-09 07:38 UTC, Minjae-An commented
소셜 로그인으로의 변경에 따른 close

2024-04-09 07:38 UTC, closed without merging